name:                url-shorter
version:             0.1.0.0
github:              "ruzen42/url-shorter"
license:             BSD-3-Clause
author:              "Jaroslav Mihajlenko"
maintainer:          "malledeferlive@gmail.com"
copyright:           "GPLv3"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            url shorter microservice
category:            Web

description:         Please see the README on GitHub at <https://github.com/ruzen42/url-shorter#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- text
- containers
- http-types
- bytestring
- pureMD5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  url-shorter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - url-shorter

tests:
  url-shorter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - url-shorter
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
